services:
  - type: web
    name: trackify-api
    env: node
    plan: free
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npx tsx src/index.ts
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: '*'
